### ISSUE TITLE
BUG: Back Button

### ISSUE THREAD

**Issue by togacharls** [togacharls/applimentate#4]
When we open applimentate directly in a sepecific section, like allergens, using a web browser, the back button is not visible

**Comment by Nitei** [comment]
The back button is visible alwais as you can check in the video wich i send
you today.

**Comment by Nitei** [comment]
Carlos, te bajaste los cambios que hice? me refiero a uno en el que cambio
el defaultHref="/" del ion-back-button

**Comment by togacharls** [comment]
Corrígeme si me equivoco pero había que añadirlo también en el listado y en el detalle de cualquier alérgeno. Prueba a acceder directamente a la URL /allergens desde el navegador. Es una chorrada, sólo habría que añadir el defaultHref

**Comment by Nitei** [comment]
Carlos a mi me funciona correctamente y tenemos los 2 el mismo repositorio,
lo que puede que ocurra es que hagas ionic serve, entres en alérgenos,
elijas el gluten por ejemplo y entras a  la vista, si le das a recargar el
<ion-back-button> desaparece pero es normal por que al recargar ya estás en
esa vista y se a limpiado el la pila del router es decir, as llegado al
ultimo paso sin pasar por otros antes de forma que no hay un historial en
el que poder volver hacia atrás y por eso se oculta, por que no hay un paso
hacia atrás sobre el que volver, es normal.

De cualquier manera estaría bien lo que dices del defaultHref así si ocurre
esto directamente vuelves a la raíz, no lo agregué al de allergenos por que
estamos en la rama del bmi y no me parecia correcto añadir un cambio de
otra rama distinta en la de bmi.

Dime qué te parece y que hago.

**Comment by togacharls** [comment]
Creo que es buena idea meterle el defaultHref ya que, en esa sección, tiene que aparecer sí o sí el botón de navegación hacia atrás ya que, de lo contrario, no habría forma de volver al HOME.
Puede que en el futuro (lo más probable es que no) implementemos un enlace externo a la aplicación que abra una página concreta de la misma. Ejemplos como éste hay un montón, por ejemplo cuando abres un anuncio de "Idealista" Android da la opción de abrirlo desde la web o desde la app.
Corrige esta chorrada cuando puedas y, al ser un bug, habría que subir una versión menor, es decir, si la versión la entendemos como X.Y.Z habría que incrementar Z en 1.

**Comment by Nitei** [comment]
Acabo de añadir el defaultHref"/" a allergens-detail.page.html y a allergens-page.html
