### ISSUE TITLE
BUG: IMG - Negatives weight/height

### ISSUE THREAD

**Issue by togacharls** [togacharls/applimentate#9]
Negatives values for **weight** or **height** shouldn't be allowed

**Comment by Nitei** [comment]
Carlos, con las pruebas automáticas acuérdate de que se hacía el bmiResult
desde morbid a slim, daba error, lo as quitado de el test, creo que debería
estar ahí por ese motivo.

**Comment by Nitei** [comment]
Carlos, acabo de solucionarlo, ahora si el peso o la altura o el bmiResult es negativo o undefined nada funciona.
